(()=>{
"use strict";
const VER="2026-09-13-curriculum-tools-v5";
if(window.__studyJewV5===VER)return;window.__studyJewV5=VER;

const DB="study-jew-curriculum-pdf", STORE="files", KEY="curriculum-minibook";
const PDFJS="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js";
const WORKER="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";
const START={"총론":3,"창체":20,"바른 생활":30,"슬기로운 생활":42,"즐거운 생활":54,"국어":66,"사회":106,"도덕":139,"수학":152,"과학":184,"실과":221,"체육":241,"음악":268,"미술":285,"영어":302};
const ORDER=Object.keys(START), ALIAS={"창의적 체험활동":"창체","창의적체험활동":"창체","바른생활":"바른 생활","슬기로운생활":"슬기로운 생활","즐거운생활":"즐거운 생활","실과(기술가정)정보":"실과"};
const S={content:false,subject:"",doc:null,blob:null,token:0,span:new Map(),busy:false};

function css(){if(document.getElementById("sjV5Style"))return;const s=document.createElement("style");s.id="sjV5Style";s.textContent=`
@media(min-width:700px) and (min-height:600px){
 #widePlannerSide{width:clamp(230px,30vw,340px)!important;max-width:340px!important;min-width:230px!important;overflow:hidden!important;overscroll-behavior-x:none!important}
 #widePlannerSide .wide-planner-inner,#widePlannerList{width:100%!important;max-width:100%!important;min-width:0!important;overflow-x:hidden!important;overscroll-behavior-x:none!important}
 #widePlannerList .planner-task,#widePlannerList .planner-task-link,#widePlannerList .planner-task-check,#widePlannerList .planner-task-exclude{touch-action:pan-y!important}
 #widePlannerList .planner-task{max-width:100%!important;min-width:0!important;left:0!important;right:auto!important;translate:0 0!important;transform:none!important}
}
.curriculum-line.curriculum-hanging{padding-left:min(var(--curriculum-hang,1.04em),1.28em)!important;text-indent:calc(-1 * min(var(--curriculum-hang,1.04em),1.28em))!important}
.sj-v5-side-btn.active{background:#303136!important;color:#fff!important;border-color:#303136!important;font-weight:750!important}
body.sj-v5-content .curriculum-page-dock{display:none!important}
.sj-v5-root{padding:2px 0 30px;max-width:100%}.sj-v5-head{position:sticky;top:0;z-index:10;display:flex;gap:6px;align-items:center;padding:7px 3px 8px;background:rgba(255,255,255,.97);border-bottom:1px solid #e4e4e7;margin-bottom:8px}.sj-v5-head strong{flex:1;min-width:0}.sj-v5-head button,.sj-v5-note button{border:1px solid #d9d9dd;background:#fff;border-radius:7px;padding:7px 9px;font:inherit;font-size:.7em;color:#55565b}.sj-v5-note{padding:12px;border:1px solid #e0e0e4;border-radius:8px;background:#fafafa;color:#696a70;font-size:.74em;line-height:1.55}.sj-v5-note b{display:block;color:#3f4045;margin-bottom:4px}.sj-v5-note button{font-size:1em;margin:8px 6px 0 0}.sj-v5-stack{display:flex;flex-direction:column;align-items:center;gap:0;width:100%;overflow-x:auto;-webkit-overflow-scrolling:touch}.sj-v5-page{display:block;height:auto;background:#fff;border-left:1px solid #dddde1;border-right:1px solid #dddde1}.sj-v5-page:first-child{border-top:1px solid #dddde1;border-radius:7px 7px 0 0}.sj-v5-page:last-child{border-bottom:1px solid #dddde1;border-radius:0 0 7px 7px}.sj-v5-progress{padding:18px 8px;text-align:center;color:#85868b;font-size:.74em}
`;
document.head.append(s)}
function toast(t){try{window.toast?.(t)}catch{} }
function curriculumOn(){const v=document.getElementById("curriculumView"),b=document.getElementById("workspaceCurriculum");return !!((v&&!v.classList.contains("hidden"))||b?.classList.contains("active"))}
function sideOn(){return curriculumOn()&&document.getElementById("widePlannerCurriculumTab")?.classList.contains("active")}
function subject(){const sel=document.querySelector("#widePlannerList .wide-curriculum-toolbar select");let s=sel?.value||document.getElementById("curriculumTitle")?.textContent||"";s=String(s).trim();return ALIAS[s]||s}
function range(sub){const s=ALIAS[sub]||sub,i=ORDER.indexOf(s);if(i<0)return null;return {s,start:START[s]+9,end:i<ORDER.length-1?START[ORDER[i+1]]+8:328}}
function standardsOn(){return !!document.querySelector("#curriculumView.curriculum-standards-summary,#curriculumPassage .curriculum-standards-v2-toolbar")}
function sourceBlank(){const tb=document.querySelector("#curriculumPassage .curriculum-standards-v2-toolbar");if(!tb)return null;return [...tb.querySelectorAll("button")].find(b=>/빈칸\s*편집/.test(b.textContent||""))||tb.querySelector("button:nth-of-type(3)")}
function toggleStandardBlank(){const b=sourceBlank();if(b){b.click();setTimeout(schedule,20);return}try{if(typeof window.curriculumUi==="function"&&typeof window.renderCurriculumStandards==="function"){const u=window.curriculumUi();u.standardBlankEdit=!u.standardBlankEdit;window.saveLocal?.();window.renderCurriculumStandards();setTimeout(schedule,20);return}}catch(e){console.warn(e)}toast("성취기준 화면을 연 뒤 다시 눌러 주세요")}

function lockX(){const inner=document.querySelector("#widePlannerSide .wide-planner-inner"),list=document.getElementById("widePlannerList");for(const el of [inner,list]){if(!el||el.dataset.sjV5x)return;el.dataset.sjV5x="1";el.addEventListener("scroll",()=>{if(el.scrollLeft!==0)el.scrollLeft=0},{passive:true})}}
function syncSide(){lockX();if(!sideOn())return;const tools=document.querySelector("#widePlannerList .wide-curriculum-study-tools");if(!tools)return;let c=tools.querySelector(".sj-v5-content-btn");if(!c){c=document.createElement("button");c.type="button";c.className="sj-v5-side-btn sj-v5-content-btn";c.textContent="내용체계";c.onclick=e=>{e.preventDefault();e.stopPropagation();if(S.content&&S.subject===subject())exitContent();else openContent(subject())};tools.insertBefore(c,tools.querySelector(".wide-curriculum-study-hint")||null)}c.disabled=!range(subject());c.classList.toggle("active",S.content&&S.subject===subject());c.textContent=S.content&&S.subject===subject()?"✓ 내용체계":"내용체계";
 let sb=tools.querySelector(".sj-v5-standard-blank");if(standardsOn()){if(!sb){sb=document.createElement("button");sb.type="button";sb.className="sj-v5-side-btn sj-v5-standard-blank";sb.onclick=e=>{e.preventDefault();e.stopPropagation();toggleStandardBlank()};tools.insertBefore(sb,tools.querySelector(".wide-curriculum-study-hint")||null)}const src=sourceBlank();sb.textContent=src?.textContent||"✎ 빈칸 편집";sb.classList.toggle("active",!!src?.classList.contains("active"));sb.disabled=false}else sb?.remove()}

function openDb(){return new Promise((resolve,reject)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE)};q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}
async function stored(){try{const db=await openDb();return await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readonly"),q=tx.objectStore(STORE).get(KEY);q.onsuccess=()=>resolve(q.result||null);q.onerror=()=>reject(q.error)})}catch{return null}}
async function save(blob){try{const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(blob,KEY);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}catch{}}
function pickPdf(){return new Promise(resolve=>{const i=document.createElement("input");i.type="file";i.accept="application/pdf,.pdf";i.style.cssText="position:fixed;left:-9999px;top:-9999px";document.body.append(i);let done=false;const finish=f=>{if(done)return;done=true;setTimeout(()=>i.remove(),0);resolve(f)};i.onchange=()=>finish(i.files?.[0]||null);i.addEventListener("cancel",()=>finish(null),{once:true});i.click()})}
function timeout(p,ms,msg){return Promise.race([p,new Promise((_,rej)=>setTimeout(()=>rej(new Error(msg)),ms))])}
async function loadPdfJs(){if(window.pdfjsLib)return window.pdfjsLib;if(window.__sjV5Pdf)return window.__sjV5Pdf;window.__sjV5Pdf=new Promise((resolve,reject)=>{const sc=document.createElement("script");sc.src=PDFJS;sc.async=true;const tm=setTimeout(()=>reject(new Error("PDF 도구 로딩 시간이 초과되었습니다")),12000);sc.onload=()=>{clearTimeout(tm);if(!window.pdfjsLib)return reject(new Error("PDF 도구를 불러오지 못했습니다"));window.pdfjsLib.GlobalWorkerOptions.workerSrc=WORKER;resolve(window.pdfjsLib)};sc.onerror=()=>{clearTimeout(tm);reject(new Error("PDF 도구를 불러오지 못했습니다"))};document.head.append(sc)});return window.__sjV5Pdf}
async function makeDoc(blob){const lib=await loadPdfJs(),buf=await blob.arrayBuffer();return await timeout(lib.getDocument({data:buf}).promise,18000,"PDF 열기 시간이 초과되었습니다")}
async function connectFile(){const f=await pickPdf();if(!f)return false;S.blob=f;S.doc=null;S.span.clear();await save(f);return true}

const compact=x=>String(x||"").replace(/[\s⋅·ㆍ]/g,"");
function lines(tc){const rows=[];for(const it of tc.items||[]){const t=String(it.str||"").trim();if(!t)continue;const y=Number(it.transform?.[5]||0);let r=rows.find(x=>Math.abs(x.y-y)<2.4);if(!r){r={y,p:[]};rows.push(r)}r.p.push({x:Number(it.transform?.[4]||0),t})}return rows.map(r=>({y:r.y,t:r.p.sort((a,b)=>a.x-b.x).map(x=>x.t).join(" ")})).sort((a,b)=>b.y-a.y)}
async function findSpan(doc,sub){if(S.span.has(sub))return S.span.get(sub);const rg=range(sub);let sp=0,ep=0,sy=null,ey=null;for(let p=rg.start;p<=Math.min(doc.numPages,rg.end);p++){const pg=await doc.getPage(p),ls=lines(await pg.getTextContent());if(!sp){const l=ls.find(x=>compact(x.t).includes("가.내용체계"));if(l){sp=p;sy=l.y}}if(sp){const l=ls.find(x=>compact(x.t).includes("나.성취기준"));if(l){ep=p;ey=l.y;break}}}if(!sp)throw new Error("PDF에서 ‘가. 내용 체계’를 찾지 못했습니다");if(!ep){ep=Math.min(doc.numPages,rg.end);ey=null}const v={sp,ep,sy,ey};S.span.set(sub,v);return v}
async function crop(pg,opt){const scale=1.5,v=pg.getViewport({scale}),full=document.createElement("canvas");full.width=Math.ceil(v.width);full.height=Math.ceil(v.height);await timeout(pg.render({canvasContext:full.getContext("2d",{alpha:false}),viewport:v}).promise,15000,"표 렌더링 시간이 초과되었습니다");const mx=Math.round(22*scale),mt=Math.round(24*scale),mb=Math.round(22*scale);let top=mt,bottom=full.height-mb;if(opt.sy!=null)top=Math.max(0,Math.round(full.height-opt.sy*scale-20*scale));if(opt.ey!=null)bottom=Math.min(full.height,Math.round(full.height-opt.ey*scale-10*scale));if(bottom<top+20){top=mt;bottom=full.height-mb}const left=mx,w=Math.max(1,full.width-mx*2),h=Math.max(1,bottom-top),out=document.createElement("canvas");out.width=w;out.height=h;out.className="sj-v5-page";out.getContext("2d",{alpha:false}).drawImage(full,left,top,w,h,0,0,w,h);full.width=1;full.height=1;return out}

function shell(sub){const passage=document.getElementById("curriculumPassage");if(!passage)return null;passage.innerHTML="";const root=document.createElement("div");root.className="sj-v5-root";const head=document.createElement("div");head.className="sj-v5-head";const title=document.createElement("strong");title.textContent=`${sub} · 내용 체계`;const change=document.createElement("button");change.type="button";change.textContent="PDF 바꾸기";change.onclick=async()=>{const ok=await connectFile();if(ok)renderConnected(sub,true)};const close=document.createElement("button");close.type="button";close.textContent="원문";close.onclick=exitContent;head.append(title,change,close);root.append(head);passage.append(root);return root}
function promptFile(root,sub,msg="이 기기에서 미니북 PDF를 한 번 연결해 주세요."){root.querySelector(".sj-v5-progress")?.remove();const n=document.createElement("div");n.className="sj-v5-note";n.innerHTML=`<b>내용 체계 PDF가 아직 연결되지 않았습니다.</b>${msg}`;const b=document.createElement("button");b.type="button";b.textContent="미니북 PDF 선택";b.onclick=async()=>{const ok=await connectFile();if(ok)renderConnected(sub,true)};n.append(document.createElement("br"),b);root.append(n)}
async function openContent(sub){const rg=range(sub);if(!rg){toast("이 과목의 내용 체계 범위를 찾을 수 없습니다");return}S.content=true;S.subject=rg.s;S.token++;document.body.classList.add("sj-v5-content");const root=shell(rg.s);if(!root)return;const p=document.createElement("div");p.className="sj-v5-progress";p.textContent="저장된 PDF를 확인하는 중…";root.append(p);syncSide();const found=S.blob||await timeout(stored(),1200,"저장 확인 시간 초과").catch(()=>null);if(!S.content||S.subject!==rg.s)return;if(!found){promptFile(root,rg.s);return}S.blob=found;renderConnected(rg.s,false)}
async function renderConnected(sub,forceDoc=false){const rg=range(sub),root=shell(rg.s);if(!root)return;const token=++S.token;const p=document.createElement("div");p.className="sj-v5-progress";p.textContent="내용 체계 표를 여는 중…";root.append(p);S.busy=true;try{if(!S.blob){const b=await stored();if(!b){promptFile(root,rg.s);return}S.blob=b}if(forceDoc)S.doc=null;if(!S.doc)S.doc=await makeDoc(S.blob);if(token!==S.token)return;p.textContent="내용 체계 위치를 찾는 중…";const x=await findSpan(S.doc,rg.s);if(token!==S.token)return;const stack=document.createElement("div");stack.className="sj-v5-stack";p.replaceWith(stack);for(let page=x.sp;page<=x.ep;page++){if(token!==S.token)return;const pg=await S.doc.getPage(page),cv=await crop(pg,{sy:page===x.sp?x.sy:null,ey:page===x.ep?x.ey:null});cv.style.width=`${Math.max(280,(document.getElementById("curriculumPassage")?.clientWidth||600)-12)}px`;stack.append(cv)}}catch(e){console.warn("content table",e);if(token!==S.token)return;p.className="sj-v5-note";p.innerHTML=`<b>내용 체계를 열지 못했습니다.</b>${String(e?.message||e)}`;const retry=document.createElement("button");retry.type="button";retry.textContent="PDF 다시 선택";retry.onclick=async()=>{const ok=await connectFile();if(ok)renderConnected(rg.s,true)};p.append(document.createElement("br"),retry)}finally{S.busy=false;syncSide()}}
function exitContent(){if(!S.content)return;S.content=false;S.token++;document.body.classList.remove("sj-v5-content");try{window.renderCurriculumCurrent?.();window.renderWidePlannerSide?.()}catch{}setTimeout(schedule,30)}

let raf=0;function schedule(){cancelAnimationFrame(raf);raf=requestAnimationFrame(syncSide)}
function install(){css();syncSide();const side=document.getElementById("widePlannerSide"),cv=document.getElementById("curriculumView");const mo=new MutationObserver(schedule);if(side)mo.observe(side,{subtree:true,childList:true,attributes:true,attributeFilter:["class"]});if(cv)mo.observe(cv,{subtree:true,childList:true,attributes:true,attributeFilter:["class"]});document.addEventListener("click",e=>{if(e.target.closest?.("#widePlannerCurriculumTab,#workspaceCurriculum,.wide-curriculum-study-tools button,.curriculum-standards-v2-toolbar button"))setTimeout(schedule,10)},true);window.addEventListener("resize",schedule,{passive:true})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install,{once:true});else install();
})();
